### ISSUE TITLE
Mnemosyne name

### ISSUE THREAD

**Issue by rvirding** [lfex/mnemosyne#1]
While this a very logical name for us old erlangers it does cause some confusion. Before we had QLCs there was a higher level interface language to mnesia which was called mnemosyne. IIRC it was more logic based in its structure and for a while there was even an :- operator which has now gone.

**Comment by oubiwann** [comment]
Ha! That's so cool! I didn't know about that.

I've just had a fun time reading about the Titan, Muses, etc. Cleo/Kleo/Kliew seemed like a nice alternative ... from "memory" to "history" but that would be a better match for a versioned database ;-) Going with the Roman version of Mnemosyne (Moneta) could work. I'm leaning that way now; but will do some more exploring :-)

**Comment by oubiwann** [comment]
Yeah, after digging around in the etymology of silos and granaries, I think maybe just "Moneta" will be fine; even the confusion with the change in the meaning of the word over time (from "memory" to "money") could be a confusion with positive associations for some ...

For me, I'll stick with memory ;-)

**Comment by oubiwann** [comment]
Project has been renamed; closing ...
